"""empty message

Revision ID: c8808358938f
Revises: f2af71f3e5cb
Create Date: 2019-11-17 17:08:13.420889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8808358938f'
down_revision = 'f2af71f3e5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stakan_ibfk_3', 'stakan', type_='foreignkey')
    op.drop_column('stakan', 'fromCoin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stakan', sa.Column('fromCoin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('stakan_ibfk_3', 'stakan', 'coins', ['fromCoin_id'], ['id'])
    # ### end Alembic commands ###
