"""empty message

Revision ID: d7a02bebd17b
Revises: da1fed858483
Create Date: 2019-11-17 16:41:55.053836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a02bebd17b'
down_revision = 'da1fed858483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'users', ['password'], unique=True)
    # ### end Alembic commands ###
