"""empty message

Revision ID: f2af71f3e5cb
Revises: d7a02bebd17b
Create Date: 2019-11-17 17:06:34.150979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2af71f3e5cb'
down_revision = 'd7a02bebd17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stakan', sa.Column('fromCoin_id', sa.Integer(), nullable=False))
    op.add_column('stakan', sa.Column('toCoin_id', sa.Integer(), nullable=False))
    op.drop_constraint('stakan_ibfk_1', 'stakan', type_='foreignkey')
    op.create_foreign_key(None, 'stakan', 'coins', ['fromCoin_id'], ['id'])
    op.create_foreign_key(None, 'stakan', 'coins', ['toCoin_id'], ['id'])
    op.drop_column('stakan', 'coin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stakan', sa.Column('coin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stakan', type_='foreignkey')
    op.drop_constraint(None, 'stakan', type_='foreignkey')
    op.create_foreign_key('stakan_ibfk_1', 'stakan', 'coins', ['coin_id'], ['id'])
    op.drop_column('stakan', 'toCoin_id')
    op.drop_column('stakan', 'fromCoin_id')
    # ### end Alembic commands ###
